### ISSUE TITLE
[Feature] Can we add a JepConfig in Jep SharedIntepreter construction

### ISSUE THREAD

**Issue by hungph** [ninia/jep#168] opened 2018-10-16 05:56 UTC
I currently changed from using Jep to using the new SharedIntepreter.
The problem is in SharedIntepreter, I can’t define a JepConfig object, because I want to redirect Python script console (print cmd) to Java by using setRedirectOutputStreams to true.

So I think it can be better if we can add a JepConfig to constructor of SharedIntepreter, or is there anyway that I don’t know that I can handle my above case?

**Comment by bsteffensmeier** [comment] 2018-10-16 13:18
The problem is that all the options in JepConfig are either invalid for a SharedInterpreter or they would be shared amongst all SharedInterpreters so I don't think it makes sense to set in the constructor. For example the stream redirection works by reassigning sys.stdout and sys.stderr. Since there is only one sys module in all SharedInterpreters the change will impact them all. So if we add JepConfig to the constructor I am concerned a user might create one SharedInterpreter with stream redirection and another without and that just won't work as expected.

For the current version of Jep I can recommend a workaround. Redirect streams normally just [evals a few statements](https://github.com/ninia/jep/blob/dev_3.8/src/main/java/jep/Jep.java#L287) so you can just do the same in your code, if you do it once in one of your shared interpreters they should all redirect:

```
interp.eval("from jep import redirect_streams");
interp.eval("redirect_streams.setup()");`
```

I would like to add a simple flag somewhere to do it for you, I just don't know where and I am open to suggestions. Ideally I would just like to add a static method like SharedInterpreter.setRedirectOutputStreams(). The staticness would nicely communicate it is a global setting. The problem is that I need an interpreter to actually setup the streams and I don't have one in a static context, so I can't make that actually work. We could pass an interpreter into the method but I worry people will get confused by that and assume they are modifying only the passed in interpreter, at that point we might as well make it a non-static method and rely on javadoc to explain the global nature of the setting.

The other option would be to make it actually work so different shared interpreters can print differently. We would have to develop a custom python stream that would check a flag within jep for every print statement to determine if it goes to java or not. I think that adds too much complexity for a use case that I doubt anyone needs, I only mention it so that if someone does actually need it they can speak now before we implement something else.

**Comment by ndjensen** [comment] 2018-10-19 15:54
I think a static method would be best to convey that it affects all SharedInterpreter instances.

We could possibly hold a JepConfig in memory like we do with sharedModulesArgv and expect anyone using SharedInterpreters to set that before initializing a SharedInterpreter.  If we went that way we could track if someone called the static method(s) after a SharedInterpreter was initialized and throw an exception telling them they have to set before instantiating any SharedInterpreters.

**Comment by mdenty** [comment] 2019-03-16 11:33
_As a reminder for myself and in the hope it will be helpful to someone._

Yesterday I had the need of passing a `JepConfig` to `SharedInterpreter` constructor too.
I've ended up by creating a class extending `Jep` with same code as `SharedInterpreter`.
I had to set IncludePath and class enquirer for my project to work.

This is the Kotlin implementation of my work.
Hopefully any maintainer of Jep could comment on this code (specially if there are major issues)

```
import jep.*

class MySharedInterpreter private constructor(config: JepConfig) : Jep(config, false) {
    private var initialized = false

    @Throws(JepException::class)
    override fun configureInterpreter(config: JepConfig) {
        synchronized(SharedInterpreter::class.java) {
            if (!initialized) {
                super.configureInterpreter(config)
                initialized = true
            }
        }

    }

    companion object {
        val jeps = ThreadLocal.withInitial { createJep() }

        private fun createJep(): Jep {
            val config = JepConfig()
                    .setInteractive(false)
                    .setIncludePath(System.getProperty("PY_INCLUDE_PATH", "/Library/Python/2.7/site-packages"))
                    .setClassEnquirer(JepClassEnquirer)

            val j = MySharedInterpreter(config)

            return j
        }
    }
}

object JepClassEnquirer: ClassEnquirer {
    override fun getClassNames(pkgName: String?): Array<String> {
        return ClassList.getInstance().getClassNames(pkgName)
    }

    override fun getSubPackages(pkgName: String?): Array<String> {
        return ClassList.getInstance().getSubPackages(pkgName)
    }

    override fun isJavaPackage(name: String?): Boolean {
        return when {
            name == "tensorflow" -> false
            packages.contains(name) -> false
            else -> ClassList.getInstance().isJavaPackage(name)
        }
    }

    private val property = System.getProperty("jep.import.blacklist", "")
    private val packages = property.split(";").toList()
}
```

**Comment by bsteffensmeier** [comment] 2019-08-23 22:10
This can be closed when 3.9 is released because SharedInterpreter can be configured with a JepConfig in change 6642ba7

**Comment by bsteffensmeier** [comment] 2019-08-29 23:49
Jep 3.9.0 has been released.

**Closed by bsteffensmeier** 2019-08-29 23:49 UTC
Labels: improvement

**Comment by lfcnassif** [comment] 2021-02-18 14:09
Hi, first thank you for this great library!

I had success to redirect my python script stderr/stdout prints to java configured logger, but messages from tensorflow-2.4 are still being printed to console. Any workaround to redirect tensorflow messages too?

**Comment by bsteffensmeier** [comment] 2021-02-18 16:48
@lfcnassif can you find where in the tensorflow code the output is coming from. We need to know how tensorflow is accessing stdout before we can know how to redirect them.

**Comment by lfcnassif** [comment] 2021-02-18 20:33
Thanks for the fast reply @bsteffensmeier!

I'm a java developer and just a very beginner in python. Just questioned to see if any of you could already know how to workaround it.

Maybe tensorflow C code is capturing the system stdout/stderr directly without checking the python configured handles...

But I'll try to take a look when some time is available.

Thanks
