### ISSUE TITLE
Feature request: specify the python virtualenv programmatically

### ISSUE THREAD

**Issue by dportabella** [ninia/jep#76] opened 2017-04-26 10:03 UTC
I have multiple python env, and I need to execute some python code in each on of the env, and compare the results.
So, I need to run different instances of Jep, each one running a different python bin or virtualenv.
It would be great to have a constructor `new Jep(pythonPath)` or new `Jep(pythonHome)`.

related: https://github.com/mrj0/jep/issues/74, https://github.com/mrj0/jep/issues/18,

**Comment by ndjensen** [comment] 2017-04-27 15:47
This seems very similar to #51.

The native Jep library is somewhat tied to the Python it was compiled against and is typically installed in that Python's site-packages folder.  Loading the single native library and then pointing at different Python environments could potentially be disastrous.

From the [JNI spec](http://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/invocation.html) it says 

> In the JDK, each class loader manages its own set of native libraries. The same JNI native library cannot be loaded into more than one class loader.

Presumably we could add support for `System.load(String absolutePath)` instead of always using `System.loadLibrary(String libraryName)` (i.e. #51).  And then you'd have to use separate classloaders and keep the ClassLoader in sync with your Jep instances, but then different versions of the native Jep library could be used.  It's not entirely clear to me how we then get the correct Python used, since typically that's set through environment variables and the JVM's environment variables cannot be changed at runtime.  (Some internet pages say it's technically feasible using JNI but recommend against it and imply the results are not guaranteed).  If we loaded the correct native Jep library, I'm not sure if that would ensure the correct Python is used or not.

**Comment by dportabella** [comment] 2017-04-28 07:24
> It's not entirely clear to me how we then get the correct Python used, since typically that's set through environment variables

if you are given the path of the python bin, such as `/Users/david/.virtualenvs/py3-data/bin/python`, then you don't need to rely on the environment variables. so, the could be a constructor such as new `Jep(pythonBinPath)`.
Would this work?
(even if only one python instance is allowed at a time)

**Comment by ndjensen** [comment] 2017-04-28 20:50
We're not using a Python executable, just the Python libraries.  That's where the embedded part comes in, it's the Java executable with the Jep and Python libraries loaded.

**Comment by dportabella** [comment] 2017-04-28 20:58
Ok, I see.

**Comment by 2014Alexander** [comment] 2017-12-28 17:21
Can you help me with:
Exception in thread "main" jep.JepException: <class 'ImportError'>: No module named 'jep'
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)
	at jep.Jep.<init>(Jep.java:376)
	at jep.Jep.<init>(Jep.java:353)
	at jep.Jep.<init>(Jep.java:302)

**Comment by ndjensen** [comment] 2018-01-02 19:43
@2014Alexander, please use the mailing list for assistance.  Your problem is most likely that you haven't installed the python site-package for jep.  You need more than the jar, you need the python files installed to your site-packages/jep directory.  Using `setup.py build install` will put them in the right location.

**Comment by bsteffensmeier** [comment] 2019-08-29 23:27
Over the last two releases several changes have been made that allow you to configure the python installation programatically through methods such as PyConfig.setPythonHome() and MainInterpreter.setJepLibraryPath so I am closing this issue. If there is a specific use case where those methods are insufficient we can reopen or start a new issue.

**Closed by bsteffensmeier** 2019-08-29 23:27 UTC
Labels: improvement

**Comment by alexander-myltsev** [comment] 2021-03-05 06:44
Hi.

Tricks with `PYTHONHOME`, `PyConfig.setPythonHome()` and `MainInterpreter.setJepLibraryPath` don't work for me.

I use [pyenv](https://github.com/pyenv/pyenv) for multiple Python environments. I put `.python-version` to my project root that requests `Python 3.8.7`. 

If I `pip install jep` to `pyenv`'s Python then `jep` works as expected. The problem is that it spoils the original Python environment: it has `jep` now and should have all other dependencies I need for the current project. Hence, all other virtualenvs that I create from `Python 3.8.7` would have those dependencies. 

To avoid it, I create `python -m venv .env` at the project root. Then `source .env/bin/activate` and `pip install jep`. 

The first problem is that I can't simply run `jep`. It fails with:

```
Python path configuration:
  PYTHONHOME = '/Users/auser/projects/aproject/.env'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Users/auser/.jenv/versions/oracle64-11.0.8/bin/java'
  sys.base_prefix = '/Users/auser/projects/aproject/.env'
  sys.base_exec_prefix = '/Users/auser/projects/aproject/.env'
  sys.executable = '/Users/auser/.jenv/versions/oracle64-11.0.8/bin/java'
  sys.prefix = '/Users/auser/projects/aproject/.env'
  sys.exec_prefix = '/Users/auser/projects/aproject/.env'
  sys.path = [
    '/Users/auser/projects/aproject/.env/lib/python38.zip',
    '/Users/auser/projects/aproject/.env/lib/python3.8',
    '/Users/auser/projects/aproject/.env/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007000027c4000 (most recent call first):
<no Python frame>
```

Explicitly exporting `PYTHONHOME` and `PYTHONPATH` to `'/Users/auser/projects/aproject/.env'` doesn't solve the problem. 

And the same error appears on my JVM application. Nevertheless, I tried to set those programmatically:

```
      MainInterpreter.setJepLibraryPath("/Users/auser/aproject/.env/lib/python3.8/site-packages/jep/libjep.jnilib")
      val pyConfig = new PyConfig()
      pyConfig.setPythonHome("/Users/asure/aproject/.env/")
      MainInterpreter.setInitParams(pyConfig)
```

How to fix that?

**Comment by ndjensen** [comment] 2021-09-15 19:27
A couple of things to try.  Since you're on Linux, you could try setting the environment variable LD_LIBRARY_PATH to the directory containing the libpython .so file.  That should make it so you don't need to set PYTHONHOME, but I'm not sure.

Another option, based on [this stackoverflow](https://stackoverflow.com/a/50233450), is to call [Py_SetPath()](https://docs.python.org/3/c-api/init.html#c.Py_SetPath)).  This will require you to modify Jep's pyembed.c and rebuild it.  I'd say do it around where we handle the PyConfig stuff, so [here](https://github.com/ninia/jep/blob/v4.0.0/src/main/c/Jep/pyembed.c#L243).

If the latter option works for you, we could potentially allow for setting the path in PyConfig too on a future release of Jep.  Please let me know if either works for you.

**Comment by josepaiva94** [comment] 2021-09-15 19:59
Creating the virtual environment with `--system-site-packages` solved it for me. No need to explicitly set python home with `PyConfig().setPythonHome("/home/user/.virtualenvs/xxx/")`.

**Comment by darkowic** [comment] 2025-05-05 12:44
I faced the `Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding` as well but found the solution. Environment:
* macos
* Spring boot application run from IntelliJ
* Python version 3.9.18 installed with Pyenv
* Virtualenv
I tried to set both `PYTHONHOME` and `PYTHONPATH` environment variables. I make sure that `jep` has been rebuild during installation (`pip install --user --force-reinstall --ignore-installed --no-cache-dir --no-build-isolation --no-binary :all: jep`) with the same python version that is used during runtime. No luck. It finally worked after building `jep` from sources. Hope it helps sb.
 
I haven't tried the `PyConfig` yet. Maybe next time.
