### ISSUE TITLE
Exception while executing a model - jep.JepException: <class 'BufferError'>: scalar buffer is readonly

### ISSUE THREAD

**Issue by pvb05** [ninia/jep#372] opened 2022-02-03 03:00 UTC
Hi,

I have a Python 3.6 example model which I am executing using Jep 4.0.1 APIs. I am instantiating a Subinterpreter to execute the model function but seeing the following error.

jep.JepException: <class 'BufferError'>: scalar buffer is readonly
	at jep.Jep.invoke(Native Method) ~[jep-4.0.1.jar:?]
	at jep.Jep.invoke(Jep.java:257) ~[jep-4.0.1.jar:?]

The same model worked fine in Jep 3.8.2. Can someone help me on what might be the reason for the failure?

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: CentOS 8.5
- Python Distribution and Version: 3.6.8
- Java Distribution and Version: OpenJDK 1.8.0
- Jep Version: 4.0.1
- Python packages used (e.g. numpy, pandas, tensorflow): numpy (1.19.5), scipy (1.5.4) and sklearn

**Comment by ndjensen** [comment] 2022-02-04 02:37
BufferError is not coming out of Jep, I think it's coming out of numpy.  Are you sure you're using the same version of Python and same version of numpy as before?

**Comment by PradeepBadiger** [comment] 2022-02-04 17:23
Hi ndjensen,
No, I rebuilt the model example for new version of Python and numpy. If I make use of Jep 3.9.1 it works fine.

**Comment by bsteffensmeier** [comment] 2022-02-04 17:52
Can you provide any sample code so we can recreate your problem or even examples of how you are passing data between python and java. The only code that impacts buffers that I am aware of in 4.0.1 allows passing python buffer objects to java and converting them to arrays automaticalyl. This would only impact you if you are using python buffer objects that are not numpy arrays and I would expect more problems from java than python if this was the case but if you are going back and forth alot this may impact you.

**Comment by bsteffensmeier** [comment] 2022-02-08 19:47
I believe this is a duplicate of #373 which has a repeatable test case. If you can, consider testing the change in the #374 against your specific use case and verify it fixes your problem.

**Comment by ndjensen** [comment] 2022-02-15 04:20
@PradeepBadiger, the newly released Jep 4.0.2 has @bsteffensmeier's fix for buffers.  Please try that release and let us know if it fixes your problem.

**Comment by PradeepBadiger** [comment] 2022-02-15 16:38
@ndjensen  - Thank you very much. I will check this out and let your know if it fixes the issue.

**Comment by bsteffensmeier** [comment] 2022-11-01 21:26
Closing due to inactivity

**Closed by bsteffensmeier** 2022-11-01 21:26 UTC
